remote_theme: pmarsceill/just-the-docs
title: Open Voice Network - Doc Site
baseurl: /docs
description: OVON published and WIP artifacts, docs, etc. 
logo: "/images/ovon-logo.jpg"
timezone: America/New_York
color_scheme: light
search_enabled: true
show_downloads: true
aux_links:
  "openvoicenetwork.org":
    - https://openvoicenetwork.org/
  "OVON Docs on GitHub":
    - "//github.com/open-voice-network/docs"
heading_anchors: true
footer_content: |
  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png"/></a>
  <br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  <br /> Copyright &copy; Open Voice Network 2017-2022
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# collections:
#   whitepapers:
#     permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   collections:
#     whitepapers:
#       name: White Papers
#       nav_exclude: false

